language: "node_js"

node_js:
  - "0.10"
  - "0.12"
  - "iojs"

branches:
  only: "master"

script: "node_modules/.bin/grunt travis"

after_script: "node_modules/.bin/codeclimate < test/lcov.info"

env:
  global:
    - secure: "b4eZwc7r8UBwP4EX8CCcYgBJQarHdSeIFl4leVPHM2K/46F83hGbtopdsi6zJzyUoGFFBzUA76pA01OgfXWfADCOgmzDL82HBkiG2rMS2c5leUC/q1tKFfuml785uQe313BDb388HYV6wBQzrsbpk//mtQ4sDn3fRBIvX+FGJWtV6HZWoqWwNcjsHXyPQrL5LUwT8ZVxcxxpxypXGdakcxiCC69KPJXQNuyQtegF5rt9i1XbsJkM+x/zD6PLLTuf0Diaivdleg4d9yuhMeumxDaeKvLI0xBRg29TN0wfef/9uhvjWlLf0BAfrPmsHSFXiKJWJ5dV//4iA7r0ZoLAaHEvRizR0FqsNiMZPjLqih+czDAMcAbogkcZWKb+TJJcZGjWDZMul4BNtIsx7bPcw5yWPUeRTLJ4R4NLu/olTZeshcAXw8BqvNZZi82xa2sWkhyInLjqi0YmhM4Mw/qtFXUhGNEqzOjimLGuaaiQ4fu969w3jWbuiooxC82TLyBa033MkI8V2KArB+LEVjvzTDyivnL10eBS7vCBjT2H4+V/h959wVmeyHYeGxjV4gcwJDHbJJpJcZ1umBJydzigRYr4fOxiFdVz3oNx/kblhSo24vIEpPdWQY22WdcYWOosInt/b3ZPLg0pSUfusVT9H/JwBM0eptxRlxaRX+OpZkE="
    - secure: "rLCJftaDbYzrS9j+zaFMvwFj6aE3yDQMJD6pa+HK/WXC36mnW0r05PNjwn5gtsTgqFuOQXUzT8LkXCk95bLnObWsUYj61vpxI+1vEOot/jXdkLd9frDM6iTBUN+5dVjAOLGxj5quGgz/+gM9RQ29bcUA7hFA6vRjRI2XxP93TQy4rEFA0y/exPzp+OyEJibAJp6c51F9QyfY5Y7+oBAvkhAXZcrdi2RzCfCtT6+jkMZTRAk1lklrWSCJK9Xd1YoLW+O4O+fS9ok6zOvK/QsHptlMoEZkSkTizSpR7x5S2iSfh9LpjdR5eI4UTPIhdyUvktHUvqis7m1qbsNMx2wqaL2mtd5FFnQ/zaczpryNX8xxxP9l9z7COlsFwYCFZAd0PZLdxVgRffRkoh2Pd4rQu84BrgSar64VKC8PYy6TD/8H1H7bUhTVLpMXUyCWZekZUHu5NdW9Nz21JUJpn/uVNcVoosa3IhQXsNgW1DraoUTrt2YWgT5GQardELKL+/wX0H7ckIHiJ0mFZ4rxKJcWgBGT1lW5xWO6cy6o1QMIIGJiy4HO1FXsNs0Ot0r8tGxZxk/0jpIaUsMnGrj5nnsmHU/YmTzGrWXFfD/FWbJPrb0ApCGTdspT+sF9Y3ZCCFa0EezSkKh2oe8LGaAwzjy4fpMpEc7ZMDyP9/OEqXbAq8I="

addons:
  code_climate:
    repo_token: "f318493b319b93c3368472cedb300ee452e5393cb5345f7fdee47eeb2bf158ab"
